language: ruby
cache: bundler
bundler_args: --without development
before_script: "bin/rake refinery:testing:dummy_app"
env:
  - DB=postgresql
  - DB=mysql
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/b5d48907cdc89864b874
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
sudo: false
